name: DynamicDungeons
version: '${project.version}'
main: com.kennedysmithjava.dynamicdungeons.Dungeons
api-version: 1.18
authors: [ KennedySmithJava ]
description: Effortlessly generate fully customizable procedurally generated dungeons